import os

PAIRS = ["BTC/USDT", "ETH/USDT", "XRP/USDT", "SOL/USDT"]
ENTRY_TIMEFRAME = "5m"
TREND_TIMEFRAME = "1h"
MAX_POSITIONS = 3
DEFAULT_RISK_PER_TRADE = 0.02
TRAINING_DAYS = 30
RETRAIN_INTERVAL_HOURS = 24
MODEL_PATH = "/app/data/model.pkl"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
